import type { Metadata } from "next";
import { Inter } from "next/font/google";

import StoreProvider from "~/lib/zustand/StoreProvider";
import ReactQueryProvider from "~/lib/react-query/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReactQueryProvider>
					{/* <StoreProvider> */}
					{children}
					{/* </StoreProvider> */}
				</ReactQueryProvider>
			</body>
		</html>
	);
}
